# Generated by Django 4.0.5 on 2022-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='students_done',
            new_name='students',
        ),
    ]
