# Generated by Django 4.0.5 on 2022-07-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_students_done_homework_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
