# Generated by Django 4.0.5 on 2022-07-09 12:01

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_homework_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.Homework.upload_path),
        ),
    ]
